In [9]:
# Import of libraries

import pandas as pd

In [10]:
# Import and display of the data frame

df = pd.read_csv('data/nfl_football_team_stats.csv')
df.head()

,Year,Date,GameNumber,GameLocation,Team,TeamScore,Opponent,OppponentScore,Result,PassingAttempts,...,KickReturnTouchdowns,KickReturnYards,PuntReturnAttempts,PuntReturnTouchdowns,PuntReturnYards,FieldGoalAttempts,FieldGoals,PuntingAttempts,PuntsBlocked,PuntingYards
0,2010,9/9/10,1,Away,Minnesota Vikings,9,New Orleans Saints,14,Loss,27,...,0,41,2,0,2,1,1,7,0,310
1,2010,9/9/10,1,Home,New Orleans Saints,14,Minnesota Vikings,9,Win,36,...,0,70,3,0,7,2,0,5,0,216
2,2010,9/12/10,1,Away,Arizona Cardinals,17,St. Louis Rams,13,Win,41,...,0,82,5,0,31,1,1,6,0,262
3,2010,9/12/10,1,Away,Atlanta Falcons,9,Pittsburgh Steelers,15,Loss,44,...,0,82,2,0,20,4,3,7,0,281
4,2010,9/12/10,1,Away,Carolina Panthers,18,New York Giants,31,Loss,35,...,0,172,2,0,38,3,3,4,0,173

In [11]:
# Changing the data type of the column 'Year' to string

df['Year'] = df['Year'].astype(str)

In [12]:
# Exporting the file

df.to_csv('nfl_football_team_stats1.csv', index = False)